# **a_tensor_initialization.py**



In [1]:
import torch

t1=torch.Tensor([1,2,3],device='cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)
t1_cpu=t1.cpu()

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
t2=torch.tensor([1,2,3],device='cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)
t2_cpu=t2.cpu()

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
a1=torch.tensor(1)
print(a1.shape,a1.ndim)

a2=torch.tensor([1])
print(a2.shape,a2.ndim)

a3=torch.tensor([1,2,3,4,5])
print(a3.shape,a3.ndim)

a4=torch.tensor([[1],[2],[3],[4],[5]])
print(a4.shape,a4.ndim)

a5=torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])
print(a5.shape,a5.ndim)

a6=torch.tensor([
    [[1],[2]],
    [[3],[4]],
    [[5],[6]]
])
print(a6.shape,a6.ndim)

a7=torch.tensor([
    [[[1],[2]]],
    [[[3],[4]]],
    [[[5],[6]]]
])
print(a7.shape,a7.ndim)

a8=torch.tensor([
    [[[1,2,3],[2,3,4]]],
    [[[3,1,1],[4,4,5]]],
    [[[5,6,2],[6,3,1]]]
])
print(a8.shape,a8.ndim)

a9=torch.tensor([
    [[[[1],[2],[3]],[[2],[3],[4]]]],
    [[[[3],[1],[1]],[[4],[4],[5]]]],
    [[[[5],[6],[2]],[[6],[3],[1]]]]
])
print(a9.shape,a9.ndim)

a10=torch.tensor([
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
])
print(a10.shape,a10.ndim)

a11=torch.tensor([
    [[1,2,3,4,5]],
    [[1,2,3,4,5]],
    [[1,2,3,4,5]],
    [[1,2,3,4,5]]
])
print(a11.shape,a11.ndim)

# a12=torch.tensor([
#     [[[1,2,3],[4,5]]],
#     [[[1,2,3],[4,5]]],
#     [[[1,2,3],[4,5]]],
#     [[[1,2,3],[4,5]]]
# ])
#print(a12.shape,a12.ndim)

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


###### **a12는 길이가 3인 [1,2,3]과 길이가 2인 [4,5]가 섞여있으므로 텐서로 변환할 수 없다.**

# **b_tensor_initialization_copy.py**

In [2]:
import numpy as np

l1=[1,2,3]
t1=torch.Tensor(l1)

l2=[1,2,3]
t2=torch.tensor(l2)

l3=[1,2,3]
t3=torch.as_tensor(l3)

l1[0]=100
l2[0]=100
l3[0]=100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [6]:
l4=np.array([1,2,3])
t4=torch.Tensor(l4)

l5=np.array([1,2,3])
t5=torch.tensor(l5)

l6=np.array([1,2,3])
t6=torch.as_tensor(l6)

l4[0]=100
l5[0]=100
l6[0]=100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


# **c_tensor_initialization_constant_values.py**

In [7]:
t1=torch.ones(size=(5,))
t1_like=torch.ones_like(input=t1)
print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [8]:
t2=torch.zeros(size=(6,))
t2_like=torch.zeros_like(input=t2)
print(t2)
print(t2_like)

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [12]:
t3=torch.empty(size=(4,))
t3_like=torch.empty_like(input=t3)
print(t3)
print(t3_like)

tensor([   inf, 1.9844, 0.0000, 2.1250])
tensor([0., nan, 0., 0.])


In [13]:
t4=torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


#### 단위행렬 생성 ####

# **d_tensor_initialization_random_values.py**

In [14]:
t1=torch.randint(low=10,high=20,size=(1,2))
print(t1)

t2=torch.rand(size=(1,3))
print(t2)

t3=torch.randn(size=(1,3))
print(t3)

t4=torch.normal(mean=10.0,std=1.0,size=(3,2))
print(t4)

t5=torch.linspace(start=0.0,end=5.0,steps=3)
print(t5)

t6=torch.arange(5)
print(t6)

tensor([[16, 18]])
tensor([[0.8520, 0.4292, 0.3491]])
tensor([[ 0.3630, -0.0433, -0.1572]])
tensor([[10.7056,  8.8932],
        [10.6702,  9.8817],
        [ 9.4642, 10.0461]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


### randint(n) : 0~n-1 사이 랜덤 숫자 추출
### rand(m,n) : 0~1 균일분포 표준정규분포 난수를 추출
### randn(m,n) : 평균0, 표준편차 1의 표준정규분포 난수를 추출

In [16]:
torch.manual_seed(1729)
random1=torch.rand(2,3)
print(random1)

random2=torch.rand(2,3)
print(random2)
print()

torch.manual_seed(1729)
random3=torch.rand(2,3)
print(random3)

random4=torch.rand(2,3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


#### seed값 고정하면 항상 같은 결과가 추출

# **e_tensor_type_conversion.py**

In [22]:
a=torch.ones((2,3))
print(a.dtype)

b=torch.ones((2,3),dtype=torch.int16)
print(b)

c=torch.rand((2,3),dtype=torch.float64)*20.
print(c)

d=b.to(torch.int32)
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 1.3056, 19.1222, 18.1333],
        [15.8734,  4.0635,  5.6361]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [27]:
double_d=torch.ones(10,2,dtype=torch.double)
short_e=torch.tensor([[1,2]],dtype=torch.short)

print(double_d) #결과 비교를 위해 추가
print(short_e) #결과 비교를 위해 추가

double_d=torch.ones(10,2).double()
short_e=torch.ones(10,2).short()

print(double_d) #결과 비교를 위해 추가
print(short_e) #결과 비교를 위해 추가

double_d=torch.zeros(10,2).to(torch.double)
short_e=torch.ones(10,2).to(dtype=torch.short)

print(double_d) #결과 비교를 위해 추가
print(short_e) #결과 비교를 위해 추가

double_d=torch.zeros(10,2).type(torch.double)
short_e=torch.ones(10,2).type(dtype=torch.short)

print(double_d.dtype) 
print(short_e.dtype) 

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 2]], dtype=torch.int16)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16

In [28]:
double_f=torch.rand(5,dtype=torch.double)
short_g=double_f.to(torch.short)
print((double_f*short_g).dtype)

torch.float64


# **f_tensor_operations.py**

In [30]:
t1=torch.ones(size=(2,3))
t2=torch.ones(size=(2,3))
t3=torch.add(t1,t2)
t4=t1+t2

print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [31]:
t5=torch.sub(t1,t2)
t6=t1-t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [32]:
t7=torch.mul(t1,t2)
t8=t1*t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [33]:
t9=torch.div(t1,t2)
t10=t1/t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# **g_tensor_operations_mm.py**

In [35]:
t1=torch.dot(
    torch.tensor([2,3]),torch.tensor([2,1])
)

print(t1,t1.size())

tensor(7) torch.Size([])


#### 벡터의 내적 계산

In [36]:
t2=torch.randn(2,3)
t3=torch.randn(3,2)
t4=torch.mm(t2,t3)
print(t4,t4.size())

tensor([[1.4960, 1.7676],
        [0.6352, 1.1901]]) torch.Size([2, 2])


#### 행렬의 곱셉만 지원하며 broadcasting을 지원하지 않는다.

In [40]:
t5=torch.randn(10,3,4)
t6=torch.randn(10,4,5)
t7=torch.bmm(t5,t6)

print(t7,t7.size())

tensor([[[-1.8865, -0.0460, -2.5700, -0.0696,  1.1455],
         [-0.7611, -1.8019, -1.3268, -0.5162,  0.6274],
         [ 0.2420,  3.2630,  1.7114, -0.7020, -0.1152]],

        [[ 0.6013,  1.1873,  1.7947, -0.3721,  2.6332],
         [-0.7489,  0.4968, -0.5831, -0.3323, -0.7490],
         [-2.7906,  0.2950, -2.3159, -0.4673, -2.7899]],

        [[ 1.5431, -0.5718, -1.4651, -4.4082, -1.3857],
         [-1.0963, -0.7875, -1.3408, -2.5856,  3.5505],
         [-0.2647,  0.2133,  0.6661,  2.4529, -0.6946]],

        [[ 5.5821, -3.7240, -2.7288, -0.7450,  0.8642],
         [-0.0455, -0.4839, -0.4886,  0.0807,  2.0154],
         [ 2.7758, -2.5967, -1.9154, -0.4937,  1.5704]],

        [[-0.8335,  0.4523, -2.4998, -0.9009, -2.5577],
         [ 2.2144,  0.9493,  2.7608, -0.6401,  4.4279],
         [ 0.4905,  2.1415,  4.0833,  0.0401,  4.5270]],

        [[ 4.7901,  0.1423,  1.1017, -0.3009, -0.7365],
         [ 0.7229, -0.8285,  0.0917, -0.7850,  0.7482],
         [ 1.5554, -0.9400, -0.0293, -

#### torch.mm은 2차원 행렬끼리의 곱만 연산가능하지만 torch.bmm은 3차원 텐서의 곱 연산만 지원한다.

# **h_tensor_operations_matmul.py**

In [41]:
t1=torch.randn(3)
t2=torch.randn(3)
print(torch.matmul(t1,t2).size())

torch.Size([])


In [42]:
t3=torch.randn(3,4)
t4=torch.randn(4)
print(torch.matmul(t3,t4).size())

torch.Size([3])


In [43]:
t5=torch.randn(10,3,4)
t6=torch.randn(4)
print(torch.matmul(t5,t6).size())

torch.Size([10, 3])


In [44]:
t7=torch.randn(10,3,4)
t8=torch.randn(10,4,5)
print(torch.matmul(t7,t8).size())

torch.Size([10, 3, 5])


In [45]:
t9=torch.randn(10,3,4)
t10=torch.randn(4,5)
print(torch.matmul(t9,t10).size())

torch.Size([10, 3, 5])


#### matmul: tensor와 tensor의 행렬곱셈을 수행하며 broadcasting을 지원한다.

# **i_tensor_broadcasting.py**

In [46]:
t1=torch.tensor([1.0,2.0,3.0])
t2=2.0
print(t1*t2)

tensor([2., 4., 6.])


In [47]:
t3=torch.tensor([[0,1],[2,4],[10,10]])
t4=torch.tensor([4,5])
print(t3-t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [49]:
t5=torch.tensor([[1.,2.],[3.,4.]])
print(t5+2.0)
print(t5-2.0)
print(t5*2.0)
print(t5/2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [50]:
def normalize(x):
    return x/255

t6=torch.randn(3,28,28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


In [52]:
t7=torch.tensor([[1,2],[0,3]])
t8=torch.tensor([[3,1]])
t9=torch.tensor([[5],[2]])
t10=torch.tensor([7])

print(t7+t8)
print(t7+t9)
print(t8+t9)
print(t7+t10)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [53]:
t11=torch.ones(4,3,2)
t12=t11*torch.rand(3,2)
print(t12.shape)

t13=torch.ones(4,3,2)
t14=t13*torch.rand(3,1)
print(t14.shape)

t15=torch.ones(4,3,2)
t16=t15*torch.rand(1,2)
print(t16.shape)

t17=torch.ones(5,3,4,1)
t18=torch.rand(3,1,1)
print((t17+t18).size())

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [54]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


**t25와 t26의 사이즈가 맞지 않아서 덧셈 연산을 수행할 수 없다.**

In [56]:
t27=torch.ones(4)*5
print(t27)

t28=torch.pow(t27,2)
print(t28)

exp=torch.arange(1.,5.)
a=torch.arange(1.,5.)
t29=torch.pow(a,exp)
print(t29)

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


# **j_tensor_indexing_slicing.py**

In [57]:
x=torch.tensor(
    [[0,1,2,3,4],
     [5,6,7,8,9],
     [10,11,12,13,14]]
)

print(x[1])
print(x[:,1])
print(x[1,2])
print(x[:,-1])

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [58]:
print(x[1:])
print(x[1:,3:])

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [61]:
y=torch.zeros((6,6))
y[1:4,2]=1
print(y)
print(y[1:4,1:4])

z=torch.tensor(
    [[1,2,3,4],
     [2,3,4,5],
     [5,6,7,8]]
)
print(z[:2])
print(z[1:,1:3])
print(z[:,1:])

z[1:,1:3]=0
print(z)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# **k_tensor_reshaping.py**

In [62]:
t1=torch.tensor([[1,2,3],[4,5,6]])
t2=t1.view(3,2)
t3=t1.reshape(1,6)
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [64]:
t4=torch.arange(8).view(2,4)
t5=torch.arange(6).view(2,3)
print(t4)
print(t5)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [65]:
t6=torch.tensor([[[1],[2],[3]]])
t7=t6.squeeze()
t8=t6.squeeze(0)
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [67]:
t9=torch.tensor([1,2,3])
t10=t9.unsqueeze(1)
print(t10)

t11=torch.tensor(
    [[1,2,3],
     [4,5,6]]
)
t12=t11.unsqueeze(1)
print(t12,t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [69]:
t13=torch.tensor([[1,2,3],[4,5,6]])
t14=t13.flatten()
print(t14)

t15=torch.tensor([[[1,2],
                   [3,4]],
                  [[5,6],
                   [7,8]]])
t16=torch.flatten(t15)
t17=torch.flatten(t15,start_dim=1)

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


#### flatten(input, start_dim=, end_dim=) : start_dim은 flatten을 시작하는 dimension을 설정해준다.

In [70]:
t18=torch.randn(2,3,5)
print(t18.shape)
print(torch.permute(t18,(2,0,1)).size())

t19=torch.tensor([[1,2,3],[4,5,6]])
t20=torch.permute(t19,dims=(0,1))
t21=torch.permute(t19,dims=(1,0))
print(t20)
print(t21)

t22=torch.transpose(t19,0,1)
print(t22)

t23=torch.t(t19)
print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# **l_tensor_concat.py**

In [71]:
t1=torch.zeros([2,1,3])
t2=torch.zeros([2,3,3])
t3=torch.zeros([2,2,3])
t4=torch.cat([t1,t2,t3],dim=1)
print(t4.shape)

torch.Size([2, 6, 3])


In [72]:
t5=torch.arange(0,3)
t6=torch.arange(3,8)

t7=torch.cat((t5,t6),dim=0)
print(t7.shape)
print(t7)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [75]:
t8=torch.arange(0,6).reshape(2,3)
t9=torch.arange(6,12).reshape(2,3)
t10=torch.cat((t8,t9),dim=0)
print(t10.size())
print(t10)

t11=torch.cat((t8,t9),dim=1)
print(t11.size())
print(t11)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [78]:
t12=torch.arange(0,6).reshape(2,3)
t13=torch.arange(6,12).reshape(2,3)
t14=torch.arange(12,18).reshape(2,3)
t15=torch.cat((t12,t13,t14),dim=0)
print(t15.size())
print(t15)

t16=torch.cat((t12,t13,t14),dim=1)
print(t16.size())
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [5]:
t17=torch.arange(0,6).reshape(1,2,3)
t18=torch.arange(6,12).reshape(1,2,3)

t19=torch.cat((t17,t18),dim=0)
print(t19.size())
print(t19)

t20=torch.cat((t17,t18),dim=1)
print(t20.size())
print(t20)

t21=torch.cat((t17,t18),dim=2)
print(t21.size())
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# **m_tensor_stacking.py**

In [6]:
t1=torch.tensor([[1,2,3],[4,5,6]])
t2=torch.tensor([[7,8,9],[10,11,12]])

t3=torch.stack([t1,t2],dim=0)
t4=torch.cat([t1.unsqueeze(dim=0),t2.unsqueeze(dim=0)],dim=0)
print(t3.shape,t3.equal(t4))

torch.Size([2, 2, 3]) True


In [9]:
t5=torch.stack([t1,t2],dim=1)
t6=torch.cat([t1.unsqueeze(dim=1),t2.unsqueeze(dim=1)],dim=1)
print(t5.shape,t5.equal(t6))

torch.Size([2, 2, 3]) True


In [8]:
t7=torch.stack([t1,t2],dim=2)
t8=torch.cat([t1.unsqueeze(dim=2),t2.unsqueeze(dim=2)],dim=2)
print(t7.shape,t7.equal(t8))

torch.Size([2, 3, 2]) True


In [14]:
t9=torch.arange(0,3)
t10=torch.arange(3,6)

print(t9.size(),t10.size())

t11=torch.stack((t9,t10),dim=0)
print(t11.size())
print(t11)

t12=torch.cat((t9.unsqueeze(0),t10.unsqueeze(0)),dim=0)
print(t11.equal(t12))


torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True


In [15]:
t13=torch.stack((t9,t10),dim=1)
print(t13.size())
print(t13)

t14=torch.cat((t9.unsqueeze(1),t10.unsqueeze(1)),dim=1)
print(t13.equal(t14))

torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


# **n_tensor_vstack_hstack.py**

In [16]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [17]:
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

torch.Size([2, 2, 3])


In [18]:
t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

t9 = torch.vstack([t7, t8])
print(t9.shape)
print(t9)

torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [19]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)

tensor([1, 2, 3, 4, 5, 6])


In [20]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [21]:
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17])
print(t18.shape)

print(t18)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


## **숙제 후기**

### 기초 데이터 과학 수업을 들으면서 학습했던 함수들도 나와서 이해하기 쉬웠던 부분도 있지만 대부분의 함수는 처음 보는 거라 공부를 열심히 해야겠다는 생각을 했습니다. 또한 이 코드를 입력하면서 이러한 tensor관련 함수가 어떻게 이용되어서 딥러닝이나 머신러닝에 활용이 되는지 궁금증이 생겼습니다.